# Site settings
title: Code Adventures
email: ruthan-dur@theironyard.com
description: "Ruthan likes sushi."
baseurl: "posts"
url: "this url is WAY OFF BASE"


# Build settings
markdown: kramdown
permalink: pretty
