# Site settings
title: Code Adventures
email: ruthan-dur@theironyard.com
description: "Ruthan once heard it said that Rails is omakase.  Sit down and have some sake."
baseurl: "base url"
url: "this url is WAY OFF BASE"


# Build settings
markdown: kramdown
permalink: pretty
